// <auto-generated />
namespace Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class titre_date_injection_imed : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(titre_date_injection_imed));
        
        string IMigrationMetadata.Id
        {
            get { return "201803131057270_titre_date_injection_imed"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
